[[server]]
name = "digitalocean"
endpoint = "https://s3provider.com"
key = "key"
secret = "secret"
region = "us-east-1"

[[authentication]]
name = "upload"
type = "credentials"
key = "key"
secret = "secret"

[[authentication]]
name = "client"
type = "web"
secret = "secret"
expires = 3600

[[oauth]]
auth = "client"
endpoint = "https://git.example.com/oauth/token/info"
scopes = ["list", "of", "required", "scopes"]

[[bucket]]
server = "digitalocean"
name = "artifacts"

[[bucket.0.access]]
permissions = ["write"]
auth = "upload"

[[bucket.0.access]]
permissions = ["read"]
auth = "client"