name: Test

on:
  push:
    branches:
    - master
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install D compiler
        uses: mihails-strasuns/setup-dlang@v1.0.5
        with:
          compiler: ldc-latest

      - uses: actions/cache@v1
        with:
          path: ~/.dub
          key: ${{ runner.os }}-dub-${{ hashFiles('**/dub.selections.json') }}
          restore-keys: |
            ${{ runner.os }}-dub-

      - name: Start containers
        run: docker-compose -f "docker-compose.yml" up -d --build

      - name: Test
        run: |
          dub test

      - name: Integration Test
        run: |
          dub -c it -b unittest

      - name: Stop containers
        if: always()
        run: |
          docker-compose logs
          docker-compose -f "docker-compose.yml" down

      - name: Build
        run: |
          dub build -b release

      - uses: actions/upload-artifact@master
        with:
          name: s3proxy
          path: s3proxy

  push:
    name: Push to hub.docker
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: actions/download-artifact@master
        with:
          name: s3proxy
          path: s3proxy

      -
        name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: skoppe/s3proxy
          tag-sha: true
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
      - uses: geekyeggo/delete-artifact@v1
        with:
          name: s3proxy
